### ISSUE TITLE
Extend/integrate/possibly reimplement opendefinition.org website

### ISSUE THREAD

**Issue by rgrp** [okfn/opendefinition#5]
* [x] #47 - switch to github pages
* [ ] #7 - Integrate licenses.opendefinition.org
* [ ] #2 - Integrate texts of licenses
* [x] Integrate versioned open definition
* [x] Have a blog or not (?)

**Comment by rgrp** [comment]
@mlinksva as i understand it of the remaining checkboxes above #2 is probably WONTFIX as we don't want to dupe the other project. #7 is in progress but is a bit item and can be dealt with separately.

If this sounds right, can we note this and close this as DONE

/cc @hlainchb

**Comment by mlinksva** [comment]
Makes sense to me.

**Comment by rgrp** [comment]
FIXED.
